export const provinceSigle = [
    'AG', 'AL', 'AN', 'AO', 'AR', 'AP', 'AT', 'AV', 'BA', 'BT',
    'BL', 'BN', 'BG', 'BI', 'BO', 'BZ', 'BS', 'BR', 'CA', 'CL',
    'CB', 'CE', 'CT', 'CZ', 'CH', 'CO', 'CS', 'CR', 'KR', 'CN',
    'EN', 'FM', 'FE', 'FI', 'FG', 'FC', 'FR', 'GE', 'GO', 'GR',
    'IM', 'IS', 'AQ', 'SP', 'LT', 'LE', 'LC', 'LI', 'LO', 'LU',
    'MC', 'MN', 'MS', 'MT', 'ME', 'MI', 'MO', 'MB', 'NA', 'NO',
    'NU', 'OG', 'OT', 'PD', 'PA', 'PR', 'PV', 'PG', 'PU', 'PE',
    'PC', 'PI', 'PT', 'PN', 'PZ', 'PO', 'RG', 'RA', 'RC', 'RE',
    'RI', 'RN', 'RM', 'RO', 'SA', 'SS', 'SV', 'SI', 'SR', 'SO',
    'SU', 'TA', 'TE', 'TR', 'TO', 'TP', 'TN', 'TV', 'TS', 'UD',
    'VA', 'VE', 'VB', 'VC', 'VR', 'VV', 'VI', 'VT'
];

export const provinceNomiCompleti = [
    'Agrigento', 'Alessandria', 'Ancona', 'Aosta', 'Arezzo', 'Ascoli Piceno', 'Asti', 'Avellino',
    'Bari', 'Barletta-Andria-Trani', 'Belluno', 'Benevento', 'Bergamo', 'Biella', 'Bologna',
    'Bolzano', 'Brescia', 'Brindisi', 'Cagliari', 'Caltanissetta', 'Campobasso', 'Caserta',
    'Catania', 'Catanzaro', 'Chieti', 'Como', 'Cosenza', 'Cremona', 'Crotone', 'Cuneo', 'Enna',
    'Fermo', 'Ferrara', 'Firenze', 'Foggia', 'Forlì-Cesena', 'Frosinone', 'Genova', 'Gorizia',
    'Grosseto', 'Imperia', 'Isernia', 'L\'Aquila', 'La Spezia', 'Latina', 'Lecce', 'Lecco', 'Livorno', 'Lodi', 'Lucca', 'Macerata', 'Mantova', 'Massa-Carrara', 'Matera', 'Messina',
    'Milano', 'Modena', 'Monza e della Brianza', 'Napoli', 'Novara', 'Nuoro', 'Ogliastra',
    'Oristano', 'Padova', 'Palermo', 'Parma', 'Pavia', 'Perugia', 'Pesaro Urbino', 'Pescara', 'Piacenza', 'Pisa', 'Pistoia', 'Pordenone', 'Potenza', 'Prato', 'Ragusa', 'Ravenna',
    'Reggio Calabria', 'Reggio Emilia', 'Rieti', 'Rimini', 'Roma', 'Rovigo', 'Salerno',
    'Sassari', 'Savona', 'Siena', 'Siracusa', 'Sondrio', 'Sud Sardegna', 'Taranto', 'Teramo',
    'Terni', 'Torino', 'Trapani', 'Trento', 'Treviso', 'Trieste', 'Udine', 'Varese', 'Venezia', 'Verbano-Cusio-Ossola', 'Vercelli', 'Verona', 'Vibo Valentia', 'Vicenza', 'Viterbo'
];


export const provinciaRegione = {
    'Agrigento': 'Sicilia',
    'Alessandria': 'Piemonte',
    'Ancona': 'Marche',
    'Aosta': 'ValdAosta',
    'Arezzo': 'Toscana',
    'Ascoli Piceno': 'Marche',
    'Asti': 'Piemonte',
    'Avellino': 'Campania',
    'Bari': 'Puglia',
    'Barletta-Andria-Trani': 'Puglia',
    'Belluno': 'Veneto',
    'Benevento': 'Campania',
    'Bergamo': 'Lombardia',
    'Biella': 'Piemonte',
    'Bologna': 'Emilia-Romagna',
    'Bolzano': 'Trentino-AltoAdige',
    'Brescia': 'Lombardia',
    'Brindisi': 'Puglia',
    'Cagliari': 'Sardegna',
    'Caltanissetta': 'Sicilia',
    'Campobasso': 'Molise',
    'Caserta': 'Campania',
    'Catania': 'Sicilia',
    'Catanzaro': 'Calabria',
    'Chieti': 'Abruzzo',
    'Como': 'Lombardia',
    'Cosenza': 'Calabria',
    'Cremona': 'Lombardia',
    'Crotone': 'Calabria',
    'Cuneo': 'Piemonte',
    'Enna': 'Sicilia',
    'Fermo': 'Marche',
    'Ferrara': 'Emilia-Romagna',
    'Firenze': 'Toscana',
    'Foggia': 'Puglia',
    'Forlì-Cesena': 'Emilia-Romagna',
    'Frosinone': 'Lazio',
    'Genova': 'Liguria',
    'Gorizia': 'Friuli-Venezia-Giulia',
    'Grosseto': 'Toscana',
    'Imperia': 'Liguria',
    'Isernia': 'Molise',
    'L\'Aquila': 'Abruzzo',
    'La Spezia': 'Liguria',
    'Latina': 'Lazio',
    'Lecce': 'Puglia',
    'Lecco': 'Lombardia',
    'Livorno': 'Toscana',
    'Lodi': 'Lombardia',
    'Lucca': 'Toscana',
    'Macerata': 'Marche',
    'Mantova': 'Lombardia',
    'Massa-Carrara': 'Toscana',
    'Matera': 'Basilicata',
    'Messina': 'Sicilia',
    'Milano': 'Lombardia',
    'Modena': 'Emilia-Romagna',
    'Monza e della Brianza': 'Lombardia',
    'Napoli': 'Campania',
    'Novara': 'Piemonte',
    'Nuoro': 'Sardegna',
    'Ogliastra': 'Sardegna',
    'Oristano': 'Sardegna',
    'Padova': 'Veneto',
    'Palermo': 'Sicilia',
    'Parma': 'Emilia-Romagna',
    'Pavia': 'Lombardia',
    'Perugia': 'Umbria',
    'Pesaro Urbino': 'Marche',
    'Pescara': 'Abruzzo',
    'Piacenza': 'Emilia-Romagna',
    'Pisa': 'Toscana',
    'Pistoia': 'Toscana',
    'Pordenone': 'Friuli-Venezia-Giulia',
    'Potenza': 'Basilicata',
    'Prato': 'Toscana',
    'Ragusa': 'Sicilia',
    'Ravenna': 'Emilia-Romagna',
    'Reggio Calabria': 'Calabria',
    'Reggio Emilia': 'Emilia-Romagna',
    'Rieti': 'Lazio',
    'Rimini': 'Emilia-Romagna',
    'Roma': 'Lazio',
    'Rovigo': 'Veneto',
    'Salerno': 'Campania',
    'Sassari': 'Sardegna',
    'Savona': 'Liguria',
    'Siena': 'Toscana',
    'Siracusa': 'Sicilia',
    'Sondrio': 'Lombardia',
    'Sud Sardegna': 'Sardegna',
    'Taranto': 'Puglia',
    'Teramo': 'Abruzzo',
    'Terni': 'Umbria',
    'Torino': 'Piemonte',
    'Trapani': 'Sicilia',
    'Trento': 'Trentino-AltoAdige',
    'Treviso': 'Veneto',
    'Trieste': 'Friuli-Venezia-Giulia',
    'Udine': 'Friuli-Venezia-Giulia',
    'Varese': 'Lombardia',
    'Venezia': 'Veneto',
    'Verbano-Cusio-Ossola': 'Piemonte',
    'Vercelli': 'Piemonte',
    'Verona': 'Veneto',
    'Vibo Valentia': 'Calabria',
    'Vicenza': 'Veneto',
    'Viterbo': 'Lazio'
};