import car from "../Assets/Images/car.jpg";
import car2 from "../Assets/Images/car2.jpg";
export const newData = [
  {
    id: 1,
    ragioneSociale: "Garver Srl",
    codFormaGiurid: "SRL",
    associazione: "confcommercio",
    address: "via del ferro 27",
    cap: "06134",
    localita: "Perugia",
    provincia: "PG",
    regione: "Umbria",
    codReg: "UMB",
    telefono1: "0755918018",
    telefono2: "",
    fax: "",
    partitaIva: "050540540",
    codiceFiscale: "CF001445444",
    email: "spiccardi@irrigazionericcini.it",
    pec: "amministragaver@legalmail.it",
    legaleRappresentante: "FabioRiccini",
    codCat: "B",
    DescrTelefoni: "07559180018",
    catAttPrincipale: "B",

    immagine: car,
    classeWaste: "Plastic",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 2,
    ragioneSociale: "DIMA STAR SRLL",
    codFormaGiurid: "SRL",
    associazione: "",
    address: "Via Vittorio Disetti ",
    cap: "23815",
    localita: "INTROBIO",
    provincia: "LC",
    regione: "LOMBARDIA",
    codReg: "LOM",
    telefono1: "0341983042",
    telefono2: "",
    fax: "",
    partitaIva: "02415060132",
    codiceFiscale: "CF02415060132",
    email: "vittorio.disetti@dimastar.it",
    pec: "dima.star@pec.it",
    legaleRappresentante: "Vittorio Disetti",
    codCat: "A",
    DescrTelefoni: "0341983042",
    catAttPrincipale: "A",

    immagine: car2,
    classeWaste: "Send",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 3,
    ragioneSociale: "Tutto Tessile Srl",
    codFormaGiurid: "SRL",
    associazione: "",
    address: "Via Matteotti 28",
    cap: "24069",
    localita: "Trescore Balneario",
    provincia: "BG",
    regione: "LOMBARDIA",
    codReg: "LOM",
    telefono1: "",
    telefono2: "035940000",
    fax: "",
    partitaIva: "04478340161",
    codiceFiscale: "CF04478340161",
    email: "tuttotessilesrl@gmail.com",
    pec: "tuttotessile@pec.buffetti.it",
    legaleRappresentante: "Marcello Moretti ",
    codCat: "E",
    DescrTelefoni: "035940000",
    catAttPrincipale: "E",

    immagine: car,
    classeWaste: "Metal",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 4,
    ragioneSociale: "MAP Spa",
    codFormaGiurid: "SPA",
    associazione: "",
    address: "Via Cristofero Colombo, 15",
    cap: "24046",
    localita: "Osio Sotto",
    provincia: "BG",
    regione: "LOMBARDIA",
    codReg: "LOM",
    telefono1: "0354825011",
    telefono2: "",
    fax: "",
    partitaIva: "00346820160",
    codiceFiscale: "CF00346820160",
    email: "fabio.carraro@mapspa.com",
    pec: "mapspa@pec.it",
    legaleRappresentante: "Antonio Sciola",
    codCat: "B",
    DescrTelefoni: "0354825011",
    catAttPrincipale: "B",

    immagine: car,
    classeWaste: "Plastic",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 5,
    ragioneSociale: "Boer Group Srl ",
    codFormaGiurid: "SRL",
    associazione: "Confimi Bergamo",
    address: "Via Stringher 14",
    cap: "33084",
    localita: "Cordenons",
    provincia: "PN",
    regione: "FRIULI-VENEZIA GIULIA",
    codReg: "FVG",
    telefono1: "0434932284",
    telefono2: "",
    fax: "0434580341",
    partitaIva: "01118360930",
    codiceFiscale: "CF01118360930",
    email: "info@boergroup.it",
    pec: "boergroup@legalmail.it",
    legaleRappresentante: "Mario Boer ",
    codCat: "B",
    DescrTelefoni: "0434932284",
    catAttPrincipale: "B",

    immagine: car2,
    classeWaste: "Plastic",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 6,
    ragioneSociale: "MAP Spa",
    codFormaGiurid: "SPA",
    associazione: "",
    address: "Via Cristofero Colombo, 15",
    cap: "24046",
    localita: "Osio Sotto",
    provincia: "BG",
    regione: "LOMBARDIA",
    codReg: "LOM",
    telefono1: "0354825011",
    telefono2: "",
    fax: "",
    partitaIva: "00346820160",
    codiceFiscale: "CF00346820160",
    email: "fabio.carraro@mapspa.com",
    pec: "mapspa@pec.it",
    legaleRappresentante: "Antonio Sciola",
    codCat: "B",
    DescrTelefoni: "0354825011",
    catAttPrincipale: "B",

    immagine: car,
    classeWaste: "Plastic",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 7,
    ragioneSociale: "Tutto Tessile Srl",
    codFormaGiurid: "SRL",
    associazione: "",
    address: "Via Matteotti 28",
    cap: "24069",
    localita: "Trescore Balneario",
    provincia: "BG",
    regione: "LOMBARDIA",
    codReg: "LOM",
    telefono1: "",
    telefono2: "035940000",
    fax: "",
    partitaIva: "04478340161",
    codiceFiscale: "CF04478340161",
    email: "tuttotessilesrl@gmail.com",
    pec: "tuttotessile@pec.buffetti.it",
    legaleRappresentante: "Marcello Moretti ",
    codCat: "E",
    DescrTelefoni: "035940000",
    catAttPrincipale: "E",

    immagine: car,
    classeWaste: "Metal",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 8,
    ragioneSociale: "DIMA STAR SRLL",
    codFormaGiurid: "SRL",
    associazione: "",
    address: "Via Vittorio Disetti ",
    cap: "23815",
    localita: "INTROBIO",
    provincia: "LC",
    regione: "LOMBARDIA",
    codReg: "LOM",
    telefono1: "0341983042",
    telefono2: "",
    fax: "",
    partitaIva: "02415060132",
    codiceFiscale: "CF02415060132",
    email: "vittorio.disetti@dimastar.it",
    pec: "dima.star@pec.it",
    legaleRappresentante: "Vittorio Disetti",
    codCat: "A",
    DescrTelefoni: "0341983042",
    catAttPrincipale: "A",

    immagine: car2,
    classeWaste: "Send",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 9,
    ragioneSociale: "Garver Srl",
    codFormaGiurid: "SRL",
    associazione: "confcommercio",
    address: "via del ferro 27",
    cap: "06134",
    localita: "Perugia",
    provincia: "PG",
    regione: "Umbria",
    codReg: "UMB",
    telefono1: "0755918018",
    telefono2: "",
    fax: "",
    partitaIva: "050540540",
    codiceFiscale: "CF001445444",
    email: "spiccardi@irrigazionericcini.it",
    pec: "amministragaver@legalmail.it",
    legaleRappresentante: "FabioRiccini",
    codCat: "B",
    DescrTelefoni: "07559180018",
    catAttPrincipale: "B",

    immagine: car,
    classeWaste: "Plastic",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 10,
    ragioneSociale: "DIMA STAR SRLL",
    codFormaGiurid: "SRL",
    associazione: "",
    address: "Via Vittorio Disetti ",
    cap: "23815",
    localita: "INTROBIO",
    provincia: "LC",
    regione: "LOMBARDIA",
    codReg: "LOM",
    telefono1: "0341983042",
    telefono2: "",
    fax: "",
    partitaIva: "02415060132",
    codiceFiscale: "CF02415060132",
    email: "vittorio.disetti@dimastar.it",
    pec: "dima.star@pec.it",
    legaleRappresentante: "Vittorio Disetti",
    codCat: "A",
    DescrTelefoni: "0341983042",
    catAttPrincipale: "A",

    immagine: car2,
    classeWaste: "Send",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
  {
    id: 11,
    ragioneSociale: "Tutto Tessile Srl",
    codFormaGiurid: "SRL",
    associazione: "",
    address: "Via Matteotti 28",
    cap: "24069",
    localita: "Trescore Balneario",
    provincia: "BG",
    regione: "LOMBARDIA",
    codReg: "LOM",
    telefono1: "",
    telefono2: "035940000",
    fax: "",
    partitaIva: "04478340161",
    codiceFiscale: "CF04478340161",
    email: "tuttotessilesrl@gmail.com",
    pec: "tuttotessile@pec.buffetti.it",
    legaleRappresentante: "Marcello Moretti ",
    codCat: "E",
    DescrTelefoni: "035940000",
    catAttPrincipale: "E",

    immagine: car,
    classeWaste: "Metal",
    quantita: "100kg",
    descrizione: "This is dummy data for texting purpose",
    seller: "OAG srl",
  },
];
